# Generated by Django 5.2.5 on 2025-11-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
