# Generated by Django 5.2.8 on 2025-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(default=1)),
                ('cliente', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('URGENTE', 'Urgente'), ('CREADO', 'Creado'), ('EN_PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='CREADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
